version: "3"
services:
  pwc-db:
    image: postgres
    container_name: pwc-db2
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.env-db
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
